name: Local storage unit testing

on:
  push:
    paths:
    - '**/local-storage.ts'
    - '**/storage.ts'
    - '**/redis-storage-testing.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run local-storage-testing
      env:
        CI: true
