name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: cd /
    - run: wget http://download.redis.io/redis-stable.tar.gz
    - run: tar xvzf redis-stable.tar.gz
    - run: cd redis-stable && make && sudo make install
    - run: ls
    - run: ./redis-server &
    - run: npm run test-redis
      env:
        CI: true
